### ISSUE TITLE
Not able to clear the enteries in Chapter details

### ISSUE THREAD

**Issue by haripriya225** [KLawJ/indian-cases#13]
Not able to clear Chapter information in ... Chapter [for Act & Rule}, if entered by mistake.

SS attached

![image](https://user-images.githubusercontent.com/42838811/68528395-2ac6ee00-0318-11ea-9915-8b552e577a9a.png)

**Comment by Athuli7** [comment]
There is a clear button. And it looks like it works at our. Please confirm

**Comment by Athuli7** [comment]
It wasn't working. Fixed. Pushed. Tested. Close after you confirm.

**Comment by haripriya225** [comment]
it is working
