### ISSUE TITLE
Cases are being uploaded without headnote

### ISSUE THREAD

**Issue by haripriya225** [KLawJ/indian-cases#2]
Able to view cases without headnotes in latest cases in citation search -

**Comment by Athuli7** [comment]
Is this the same issue as ICO Citations that we had fixed before?

**Comment by haripriya225** [comment]
Yes.. it is appearing in latest cases tab also

**Comment by haripriya225** [comment]
https://indiancases.com/tabs/citation .... Not able to check in which all pages the cases without headnotes are appearing in the link mentioned above... Is there any mechanism to check apart from manually verifying all cases... please inform us so that it can be checked....

**Comment by Athuli7** [comment]
Journal #231: Unreported Cases
Journal #5: Latest Cases

Same query condition as Journal #79 added.

To be confirmed.

**Comment by Athuli7** [comment]
##Latest cases

### Before deployment,

2019 ICO 2375
2019 ICO 2376
2019 ICO 2352
2019 ICO 2354
2019 ICO 2331
2019 ICO 2332
2019 ICO 2333
2019 ICO 2334
2019 ICO 2345
2019 ICO 2337
2019 ICO 2343
2019 ICO 2344
2019 ICO 2347
2019 ICO 2328
2019 ICO 2338
2019 ICO 2339
2019 ICO 2319
2019 ICO 2329
2019 ICO 2335
2019 ICO 2341
2019 ICO 2356
2019 ICO 2330
2019 ICO 2340
2019 ICO 2353
2019 ICO 2266

### After deployment,

2019 ICO 2352
2019 ICO 2354
2019 ICO 2331
2019 ICO 2332
2019 ICO 2333
2019 ICO 2334
2019 ICO 2345
2019 ICO 2337
2019 ICO 2343
2019 ICO 2344
2019 ICO 2347
2019 ICO 2328
2019 ICO 2338
2019 ICO 2339
2019 ICO 2319
2019 ICO 2335
2019 ICO 2341
2019 ICO 2356
2019 ICO 2330
2019 ICO 2340
2019 ICO 2353
2019 ICO 2266
2019 ICO 2267
2019 ICO 2323
2019 ICO 2348

**Comment by Athuli7** [comment]
2019 ICO 2375 & 2019 ICO 2376 didn't have headnotes.
2019 ICO 2352 had QC completed headnotes.

Closing as the issue looks fixed. 

**_Please reopen if you find it not to be._**
