### ISSUE TITLE
Check box for shortheadnote

### ISSUE THREAD

**Issue by haripriya225** [KLawJ/indian-cases#3]
In add headnote page. the tick mark for Shortheadnote is not getting saved

**Comment by Athuli7** [comment]
An issue with `fields/checkbox.blade.php`. Waiting for the backpack team.
Using `select2_from_array.blade.php` as a temporary measure for all mandatory checkboxes.

**Comment by Athuli7** [comment]
Closing till notice from the Backpack team.
