### ISSUE TITLE
Assignments are removed when the cases are published

### ISSUE THREAD

**Issue by haripriya225** [KLawJ/indian-cases#7]
Assignments are removed when the cases are published. This would create an issue for dummycases

**Comment by Athuli7** [comment]
Assignments are removed when a case is pushed for QC. This becomes an issue when dummy accounts are used for headnote allotment.

**Comment by Athuli7** [comment]
The rule is set to ```retain Allotment during QC```. Assign this perm to people whose allotments are not to be removed when the case is pushed to QC.
